node('nodejs') {
  stage 'build'
  openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')

  stage 'deploy'
  input message: 'Do you want to proceed?', ok: 'Proceed'
  openshiftDeploy(deploymentConfig: 'nodejs-ex')
}
